### PR TITLE
Add to list of open-source projects using Sling

### PR DESCRIPTION
**Pull request by dghubble**

### CODE REVIEW

**Comment by dghubble** [comment]
Ok to list your projects? @ajvb @drinkin @GeorgeErickson

**Comment by ajvb** [comment]
Yeah absolutely

**Comment by GeorgeErickson** [comment]
Yea absolutely, once I get some free time I want to open-source the twilio, postmark, goinstant and smartystreet api clients I wrote with sling.

**Comment by dghubble** [comment]
woo, I'm excited for those

**Pull request merged**
