### PR TITLE
[FEAUTRE] Implement custom Decoders

### PR DESCRIPTION
**Pull request by im-kulikov**
Do not close response if we does not try to decode

---

**_UPD: rewrites for implement custom decoders_**

### CODE REVIEW

**Comment by im-kulikov** [comment]
@dghubble ping?

**Comment by dghubble** [comment]
Currently, the response body is always closed for clients. With this change it would only be closed if certain arguments are given. Seems unintuitive and also breaking.

If you wish to decode responses yourself, why not just use Sling as the request builder (it gives you a `http.Request`) and send it yourself?

**Comment by im-kulikov** [comment]
@dghubble mb we can do an decoder? By default it would be json.. what you think about this solution?..

**Comment by im-kulikov** [comment]
@dghubble what you think now?

**Comment by im-kulikov** [comment]
@dghubble ping?

**Comment by dghubble** [comment]
I'll take a look soonish. New features are low priority in the backlog.

**Comment by im-kulikov** [comment]
@dghubble oh, okay 👌

**Comment by im-kulikov** [comment]
it does not break compatibility

**Comment by im-kulikov** [comment]
@dghubble any updates?

**Comment by im-kulikov** [comment]
@dghubble any updates?

**Pull request closed without merging**
